import {
  AppstoreOutlined,
  BarChartOutlined,
  BarcodeOutlined,
  CloudOutlined,
  DesktopOutlined,
  FileOutlined,
  PieChartOutlined,
  ShopOutlined,
  TeamOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  HddOutlined,
  FundOutlined,
  SettingOutlined,
} from "@ant-design/icons";

export const icon = {
  AppstoreOutlined: <AppstoreOutlined />,
  BarChartOutlined: <BarcodeOutlined />,
  BarChartOutlined: <BarChartOutlined />,
  CloudOutlined: <CloudOutlined />,
  DesktopOutlined: <DesktopOutlined />,
  FileOutlined: <FileOutlined />,
  PieChartOutlined: <PieChartOutlined />,
  ShopOutlined: <ShopOutlined />,
  TeamOutlined: <TeamOutlined />,
  UserOutlined: <UserOutlined />,
  UploadOutlined: <UploadOutlined />,
  VideoCameraOutlined: <VideoCameraOutlined />,
  HddOutlined: <HddOutlined />,
  FundOutlined: <FundOutlined />,
  SettingOutlined: <SettingOutlined />,
};
